1. What is a Python library? Why do we use Python libraries?


A Python library is a collection of related modules. It contains bundles of pre-written code that can be used repeatedly in different programs. Each module in a Python library serves a specific purpose. Libraries in Python can contain precompiled codes, documentation, configuration data, message templates, classes, and values, etc.       



We use Python libraries for several reasons:     

**Efficiency**: Libraries make everyday tasks more efficient. They save time and effort as programmers don’t need to write the same code again and again for different programs.   
**Simplicity**: They make Python programming simpler and more convenient for the programmer.    
**Functionality**: Python libraries provide access to a wide variety of operations that can be performed using the methods and variables found in any Python library.     
**Specialization**: Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

2. What is the difference between Numpy array and List?

Both Numpy arrays and Python lists are used for storing data, but they have some key differences:  


**Numpy Arrays:**   

**Homogeneous Data**: Numpy arrays store elements of the same data type, making them more compact and memory-efficient than lists.   
**Fixed Data Type**: Numpy arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.   
**Efficient Operations**: Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.   
**Memory Management**: Elements of a Numpy array are stored contiguously in memory.


**Python Lists:**   

**Heterogeneous Data**: Python lists can hold different data types.   
**Dynamic Size**: You can append elements to a list, but you can’t change the size of a Numpy array without making a full copy.   
**Memory Fragmentation**: Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.    
**General Purpose**: Lists are generally used as general-purpose data structures.


In practice, Numpy arrays are faster for vectorial functions than mapping functions to lists. However, if you need to access single items in the array, Numpy will need to box/unbox the number into a Python numeric object, which can make it slow in certain situations. On the other hand, Python lists are more flexible as they can hold heterogeneous data.

3. Find the shape, size and dimension of the following array?   
[[1, 2, 3, 4],   
[5, 6, 7, 8],   
[9, 10, 11, 12]]   

In [1]:

import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Shape: number of rows and columns
print("Shape:", array.shape)

# Size: total number of elements
print("Size:", array.size)

# Dimension: number of axes (rows, columns, etc.)
print("Dimension:", array.ndim)


Shape: (3, 4)
Size: 12
Dimension: 2


4. Write python code to access the first row of the following array?    
[[1, 2, 3, 4],  
[5, 6, 7, 8],   
[9, 10, 11, 12]]

In [2]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing the first row
first_row = array[0]

print("First row:", first_row)


First row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?   
[[1, 2, 3, 4],   
[5, 6, 7, 8],   
[9, 10, 11, 12]]

In [3]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing the element at the third row and fourth column
element = array[2, 3]

print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?  
[[1, 2, 3, 4],   
[5, 6, 7, 8],   
[9, 10, 11, 12]]

In [5]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Extracting odd-indexed elements
odd_indexed_elements = array[::2, ::2]

print("Odd-indexed elements:", odd_indexed_elements)


Odd-indexed elements: [[ 1  3]
 [ 9 11]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.0742632  0.46993977 0.02036177]
 [0.41062179 0.04318102 0.71054704]
 [0.88188562 0.11980013 0.2961363 ]]


8. Describe the difference between np.random.rand and np.random.randn?

The main difference between np.random.rand and np.random.randn lies in the statistical distribution from which they draw their random numbers:  


**np.random.rand**: This function generates random numbers from a uniform distribution over the interval [0, 1). In a uniform distribution, all values within the given interval are equally likely to be drawn.   
**np.random.randn**: This function generates random numbers from a normal (or Gaussian) distribution with a mean of 0 and a variance of 112. In a normal distribution, values closer to the mean (in this case, 0) are more likely to be drawn.  
These two functions are used in different scenarios depending on the statistical properties you want your random numbers to have. For example, np.random.randn is often used when initializing weights in neural networks because weights initialized from a normal distribution tend to work better in deep learning

9. Write code to increase the dimension of the following array?  
[[1, 2, 3, 4],   
[5, 6, 7, 8],   
[9, 10, 11, 12]]

In [10]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increasing the dimension using np.expand_dims
expanded_array = np.expand_dims(array, axis=0)

print("Expanded array:")
print(expanded_array)

# Increasing the dimension using np.newaxis
expanded_array2 = array[np.newaxis, :, :]

print("Expanded array (using np.newaxis):")
print(expanded_array2)


Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Expanded array (using np.newaxis):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?  
[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12]]

In [11]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transposing the array using np.transpose
transposed_array = np.transpose(array)

print("Transposed array:")
print(transposed_array)

# Transposing the array using the .T attribute
transposed_array2 = array.T

print("Transposed array (using .T attribute):")
print(transposed_array2)


Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Transposed array (using .T attribute):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:  
Matrix A:  [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12],[13,14,15,16]]   
Matrix B:  [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12],[13,14,15,16]]   
Perform the following operation using Python:   
 1. index wise multiplication
 2. Matrix multiplication
 3. Add both the Matrics
 4. Subtract matrix B from A
 5. Divide Matrix B by A

In [18]:
import numpy as np

# Matrix A
matrix_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],[13,14,15,16]])

# Matrix B
matrix_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],[13,14,15,16]])

# 1. Index-wise multiplication
index_wise_multiplication = matrix_a * matrix_b
print("Index-wise multiplication:\n", index_wise_multiplication)

# 2. Matrix multiplication
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("Matrix multiplication:\n", matrix_multiplication)

# 3. Add both matrices
matrix_addition = matrix_a + matrix_b
print("Matrix addition:\n", matrix_addition)

# 4. Subtract matrix B from A
matrix_subtraction = matrix_a - matrix_b
print("Matrix subtraction (A - B):\n", matrix_subtraction)

# 5. Divide matrix B by A
matrix_division = matrix_b / matrix_a
print("Matrix division (B / A):\n", matrix_division)


Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]
Matrix multiplication:
 [[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
Matrix addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Matrix subtraction (A - B):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix division (B / A):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the **byteswap()** method to swap the byte order of an array. This method toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place1. Here’s an example:



In [27]:
import numpy as np

# Define an array
A = np.array([1, 256, 8755], dtype=np.int16)

# Swap the bytes of the array elements
A.byteswap(inplace=True)

array([  256,     1, 13090], dtype=int16)

13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. The multiplicative inverse of a matrix is such that when it is multiplied by the original matrix, it results in the identity matrix.


In [32]:
import numpy as np

# Define a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)

print("inverse of matrix A:\n",A_inv)

# Verify that A_inv is indeed the inverse of A
print(np.allclose(np.dot(A, A_inv), np.eye(2)))  # Should print: True
print(np.allclose(np.dot(A_inv, A), np.eye(2)))  # Should print: True

inverse of matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
True
True


In this example, np.linalg.inv computes the inverse of the matrix A, and np.allclose checks if the product of A and A_inv (in both orders) is close to the identity matrix.  

The significance of this function lies in its wide range of applications in linear algebra, including solving systems of linear equations, finding the determinant of a matrix, and more. However, it’s worth noting that not all matrices have an inverse, and np.linalg.inv will raise a LinAlgError if the matrix is not invertible.

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. The new shape should be compatible with the original shape. If an integer is passed, then the result will be a 1-D array of that length. One shape dimension can be -1, in which case, the value is inferred from the length of the array and remaining dimensions.

In [33]:
import numpy as np

# Define an array
a = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 array
b = np.reshape(a, (2, 3))

print(b)

[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful feature that allows mathematical operations to be performed between arrays of different shapes. The term “broadcasting” describes how NumPy treats arrays with different shapes during arithmetic operations.  


Here’s how it works:


Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.    
Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.  
It does this without making needless copies of data and usually leads to efficient algorithm implementations.  


For example, if you have a 1-D array and a scalar, you can think of the scalar being stretched during the arithmetic operation into an array with the same shape as the 1-D array. The new elements in the scalar are simply copies of the original scalar.

However, NumPy is smart enough to use the original scalar value without actually making copies, so that broadcasting operations are as memory and computationally efficient as possible.

In [34]:
import numpy as np

# 1-D array
array1 = np.array([1, 2, 3])

# scalar
number = 5

# add scalar and 1-D array
sum = array1 + number

print(sum)  # Output: [6 7 8]

[6 7 8]
